export const ADD_TO_EXPRESSION = 'ADD_TO_EXPRESSION'
export const EVALUATE_EXPRESSION = 'EVALUATE_EXPRESSION'
export const RESET_RESULT = 'RESET_RESULT'
export const DELETE_CHAR_EXPRESSION = 'DELETE_CHAR_EXPRESSION'